export const game = {
	gameOver: true,
	difficulty: 3,
	speed: 1000,
	round: 1,
	startButton: document.getElementById('btn-start'),
	redButton: document.getElementById('btnred'),
	blueButton: document.getElementById('btnblue'),
	greenButton: document.getElementById('btngreen'),
	yellowButton: document.getElementById('btnyellow'),
	purpleButton: document.getElementById('btnpurple'),
	status: document.getElementById('status'),
	popup: document.getElementById('final-popup'),
	gameDomArr: [],
	runState: null,
	simonArr: [],
	simonCount: 0,
	playerArr: [],
	playerCount: 0
};
